[phases.setup]
nixPkgs = ["python312Full", "postgresql"]
env = { PIP_DISABLE_PIP_VERSION_CHECK = "1", PYTHONUNBUFFERED = "1" }

[phases.install]
cmds = [
	"cd backend && python -m ensurepip --upgrade",
	"cd backend && python -m pip install --upgrade pip",
	"cd backend && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
